#! /bin/sh

# Halt on error
set -e

# Remove our configuration
[ -L /etc/systemd/timesyncd.conf ] && rm -fv /etc/systemd/timesyncd.conf

# Restore the original configuration
dpkg-divert --remove --package mdebian-ntp --rename --divert /etc/systemd/timesyncd.conf.backup /etc/systemd/timesyncd.conf
