#! /bin/sh

# Halt on error
set -e

# Get OS name
OS=$(lsb_release -is)

# Backup the previous configuration
[ "$OS" = "Debian" ] && dpkg-divert --add --package mdebian-base --rename --divert /etc/apt/sources.list.backup /etc/apt/sources.list
dpkg-divert --add --package mdebian-base --rename --divert /etc/issue.backup /etc/issue
dpkg-divert --add --package mdebian-base --rename --divert /etc/motd.backup /etc/motd
dpkg-divert --add --package mdebian-base --rename --divert /etc/bash.bashrc.backup /etc/bash.bashrc
dpkg-divert --add --package mdebian-base --rename --divert /etc/skel/.bashrc.backup /etc/skel/.bashrc

# Install our configuration
[ "$OS" = "Debian" ] && ln -sfv /etc/apt/sources.list.mdebian /etc/apt/sources.list
ln -sfv /etc/issue.mdebian /etc/issue
ln -sfv /etc/motd.mdebian /etc/motd
ln -sfv /etc/bash.bashrc.mdebian /etc/bash.bashrc

# Remove root's .bashrc files
if [ -e /root/.bashrc ] && [ ! -e /root/.bashrc.backup ]; then
	mv -fv /root/.bashrc /root/.bashrc.backup
fi

# Remove local users' .bashrc files
for USERHOME in $(ls /home); do
	if [ "$USERHOME" = 'lost+found' ]; then continue; fi
	if [ -e /home/$USERHOME/.bashrc ] && [ ! -e /home/$USERHOME/.bashrc.backup ]; then
		mv -fv /home/$USERHOME/.bashrc /home/$USERHOME/.bashrc.backup
	fi
done
unset USERHOME

# Add the directory for local BASH configurations
mkdir -v /etc/bashrc.d || true

# Active and restart the NTP client service
timedatectl set-ntp true
systemctl restart systemd-timesyncd.service
