#! /bin/sh

# Halt on error
set -e

# Backup previous apt sources configuration
dpkg-divert --add --package mdebian-apt --rename --divert /etc/apt/sources.list.backup /etc/apt/sources.list

# Setup APT source servers in France
ln -sfv /etc/apt/sources.list.mdebian /etc/apt/sources.list
