#! /bin/sh

# Halt on error
set -e

# Remove our configuration
[ -L /etc/apt/sources.list ] && rm -fv /etc/apt/sources.list

# Restore the original configuration
dpkg-divert --remove --package mdebian-apt --rename --divert /etc/apt/sources.list.backup /etc/apt/sources.list
