#! /bin/sh

# Halt on error
set -e

# Remove our banners
[ -L /etc/issue ] && rm -fv /etc/issue
[ -L /etc/motd ] && rm -fv /etc/motd

# Restore the previous banners
dpkg-divert --remove --package mdebian-banner --rename --divert /etc/issue.backup /etc/issue
dpkg-divert --remove --package mdebian-banner --rename --divert /etc/motd.backup /etc/motd
